// Generated by scripts/gen-artifact.mjs from contracts/dust_covenant.ark.
// Do not edit: `pnpm artifact` rewrites it and CI diffs the result.
export const V2_ARTIFACT = {
    "contractName": "DustCovenant",
    "constructorInputs": [
        {
            "name": "receiverKey",
            "type": "pubkey"
        },
        {
            "name": "senderKey",
            "type": "pubkey"
        },
        {
            "name": "operatorKey",
            "type": "pubkey"
        },
        {
            "name": "operatorSignerKey",
            "type": "pubkey"
        },
        {
            "name": "operatorSats",
            "type": "int"
        },
        {
            "name": "loan",
            "type": "int"
        },
        {
            "name": "locktime",
            "type": "int"
        },
        {
            "name": "exitDelay",
            "type": "int"
        },
        {
            "name": "hasAsset",
            "type": "int"
        },
        {
            "name": "assetTxid",
            "type": "bytes32"
        },
        {
            "name": "assetGidx",
            "type": "int"
        },
        {
            "name": "assetFare",
            "type": "int"
        }
    ],
    "functions": [
        {
            "name": "recycle",
            "arkade": {
                "inputs": [],
                "asm": [
                    "<assetFare>",
                    "<assetGidx>",
                    "<assetTxid>",
                    "<hasAsset>",
                    "<operatorSats>",
                    "<operatorKey>",
                    "<receiverKey>",
                    "OP_PUSHCURRENTINPUTINDEX",
                    "0",
                    "OP_EQUALVERIFY",
                    "OP_INSPECTNUMINPUTS",
                    "2",
                    "OP_EQUALVERIFY",
                    "1",
                    "OP_INSPECTINPUTSCRIPTPUBKEY",
                    "OP_NIP",
                    "1",
                    "OP_EQUALVERIFY",
                    "1",
                    "OP_INSPECTINPUTSCRIPTPUBKEY",
                    "OP_DROP",
                    "OP_OVER",
                    "OP_EQUALVERIFY",
                    "0",
                    "OP_INSPECTOUTPUTVALUE",
                    "OP_3",
                    "OP_PICK",
                    "OP_EQUALVERIFY",
                    "0",
                    "OP_INSPECTOUTPUTSCRIPTPUBKEY",
                    "OP_NIP",
                    "1",
                    "OP_EQUALVERIFY",
                    "0",
                    "OP_INSPECTOUTPUTSCRIPTPUBKEY",
                    "OP_DROP",
                    "OP_ROT",
                    "OP_EQUALVERIFY",
                    "1",
                    "OP_INSPECTOUTPUTSCRIPTPUBKEY",
                    "OP_NIP",
                    "1",
                    "OP_EQUALVERIFY",
                    "1",
                    "OP_INSPECTOUTPUTSCRIPTPUBKEY",
                    "OP_DROP",
                    "OP_SWAP",
                    "OP_EQUALVERIFY",
                    "1",
                    "OP_INSPECTOUTPUTVALUE",
                    "0",
                    "OP_INSPECTINPUTVALUE",
                    "1",
                    "OP_INSPECTINPUTVALUE",
                    "OP_ADD",
                    "OP_ROT",
                    "OP_SUB",
                    "OP_EQUALVERIFY",
                    "1",
                    "OP_EQUAL",
                    "OP_IF",
                    "OP_2",
                    "OP_PICK",
                    "0",
                    "OP_GREATERTHAN",
                    "OP_IF",
                    "0",
                    "OP_OVER",
                    "OP_3",
                    "OP_PICK",
                    "OP_INSPECTOUTASSETLOOKUP",
                    "OP_VERIFY",
                    "OP_3",
                    "OP_PICK",
                    "OP_EQUALVERIFY",
                    "OP_ENDIF",
                    "0",
                    "1",
                    "OP_2",
                    "OP_PICK",
                    "OP_4",
                    "OP_PICK",
                    "OP_INSPECTINASSETLOOKUP",
                    "OP_NIP",
                    "OP_IF",
                    "1",
                    "OP_2",
                    "OP_PICK",
                    "OP_4",
                    "OP_PICK",
                    "OP_INSPECTINASSETLOOKUP",
                    "OP_VERIFY",
                    "OP_NIP",
                    "OP_ENDIF",
                    "1",
                    "OP_2",
                    "OP_PICK",
                    "OP_4",
                    "OP_PICK",
                    "OP_INSPECTOUTASSETLOOKUP",
                    "OP_VERIFY",
                    "0",
                    "OP_3",
                    "OP_PICK",
                    "OP_5",
                    "OP_PICK",
                    "OP_INSPECTINASSETLOOKUP",
                    "OP_VERIFY",
                    "OP_ROT",
                    "OP_ADD",
                    "OP_4",
                    "OP_PICK",
                    "OP_SUB",
                    "OP_EQUALVERIFY",
                    "OP_ENDIF",
                    "OP_1",
                    "OP_NIP",
                    "OP_NIP",
                    "OP_NIP"
                ]
            },
            "leaves": [
                {
                    "name": "recycle",
                    "witness": [
                        {
                            "name": "serverSig",
                            "type": "signature",
                            "encoding": "schnorr-64",
                            "injected": true
                        },
                        {
                            "name": "emulatorSig",
                            "type": "signature",
                            "encoding": "schnorr-64",
                            "injected": true
                        }
                    ],
                    "asm": [
                        "<SERVER_KEY>",
                        "OP_CHECKSIGVERIFY",
                        "<EMULATOR_KEY:recycle>",
                        "OP_CHECKSIG"
                    ]
                }
            ]
        },
        {
            "name": "purchase",
            "arkade": {
                "inputs": [],
                "asm": [
                    "<assetGidx>",
                    "<assetTxid>",
                    "<hasAsset>",
                    "<receiverKey>",
                    "OP_PUSHCURRENTINPUTINDEX",
                    "0",
                    "OP_EQUALVERIFY",
                    "0",
                    "OP_INSPECTOUTPUTSCRIPTPUBKEY",
                    "OP_NIP",
                    "1",
                    "OP_EQUALVERIFY",
                    "0",
                    "OP_INSPECTOUTPUTSCRIPTPUBKEY",
                    "OP_DROP",
                    "OP_SWAP",
                    "OP_EQUALVERIFY",
                    "0",
                    "OP_INSPECTOUTPUTVALUE",
                    "0",
                    "OP_INSPECTINPUTVALUE",
                    "OP_EQUALVERIFY",
                    "1",
                    "OP_EQUAL",
                    "OP_IF",
                    "0",
                    "OP_OVER",
                    "OP_3",
                    "OP_PICK",
                    "OP_INSPECTOUTASSETLOOKUP",
                    "OP_VERIFY",
                    "0",
                    "OP_2",
                    "OP_PICK",
                    "OP_4",
                    "OP_PICK",
                    "OP_INSPECTINASSETLOOKUP",
                    "OP_VERIFY",
                    "OP_EQUALVERIFY",
                    "OP_ENDIF",
                    "OP_1",
                    "OP_NIP",
                    "OP_NIP"
                ]
            },
            "leaves": [
                {
                    "name": "purchase",
                    "witness": [
                        {
                            "name": "serverSig",
                            "type": "signature",
                            "encoding": "schnorr-64",
                            "injected": true
                        },
                        {
                            "name": "emulatorSig",
                            "type": "signature",
                            "encoding": "schnorr-64",
                            "injected": true
                        }
                    ],
                    "asm": [
                        "<SERVER_KEY>",
                        "OP_CHECKSIGVERIFY",
                        "<EMULATOR_KEY:purchase>",
                        "OP_CHECKSIG"
                    ]
                }
            ]
        },
        {
            "name": "repayRefund",
            "arkade": {
                "inputs": [],
                "asm": [
                    "<assetGidx>",
                    "<assetTxid>",
                    "<hasAsset>",
                    "<loan>",
                    "<operatorKey>",
                    "OP_PUSHCURRENTINPUTINDEX",
                    "0",
                    "OP_EQUALVERIFY",
                    "OP_INSPECTNUMINPUTS",
                    "2",
                    "OP_EQUALVERIFY",
                    "1",
                    "OP_INSPECTINPUTSCRIPTPUBKEY",
                    "OP_NIP",
                    "1",
                    "OP_EQUALVERIFY",
                    "1",
                    "OP_INSPECTOUTPUTSCRIPTPUBKEY",
                    "OP_NIP",
                    "1",
                    "OP_EQUALVERIFY",
                    "1",
                    "OP_INSPECTOUTPUTSCRIPTPUBKEY",
                    "OP_DROP",
                    "1",
                    "OP_INSPECTINPUTSCRIPTPUBKEY",
                    "OP_DROP",
                    "OP_EQUALVERIFY",
                    "0",
                    "OP_INSPECTOUTPUTVALUE",
                    "OP_2",
                    "OP_PICK",
                    "OP_EQUALVERIFY",
                    "0",
                    "OP_INSPECTOUTPUTSCRIPTPUBKEY",
                    "OP_NIP",
                    "1",
                    "OP_EQUALVERIFY",
                    "0",
                    "OP_INSPECTOUTPUTSCRIPTPUBKEY",
                    "OP_DROP",
                    "OP_SWAP",
                    "OP_EQUALVERIFY",
                    "1",
                    "OP_INSPECTOUTPUTVALUE",
                    "0",
                    "OP_INSPECTINPUTVALUE",
                    "1",
                    "OP_INSPECTINPUTVALUE",
                    "OP_ADD",
                    "OP_ROT",
                    "OP_SUB",
                    "OP_EQUALVERIFY",
                    "1",
                    "OP_EQUAL",
                    "OP_IF",
                    "0",
                    "1",
                    "OP_2",
                    "OP_PICK",
                    "OP_4",
                    "OP_PICK",
                    "OP_INSPECTINASSETLOOKUP",
                    "OP_NIP",
                    "OP_IF",
                    "1",
                    "OP_2",
                    "OP_PICK",
                    "OP_4",
                    "OP_PICK",
                    "OP_INSPECTINASSETLOOKUP",
                    "OP_VERIFY",
                    "OP_NIP",
                    "OP_ENDIF",
                    "1",
                    "OP_2",
                    "OP_PICK",
                    "OP_4",
                    "OP_PICK",
                    "OP_INSPECTOUTASSETLOOKUP",
                    "OP_VERIFY",
                    "0",
                    "OP_3",
                    "OP_PICK",
                    "OP_5",
                    "OP_PICK",
                    "OP_INSPECTINASSETLOOKUP",
                    "OP_VERIFY",
                    "OP_ROT",
                    "OP_ADD",
                    "OP_EQUALVERIFY",
                    "OP_ENDIF",
                    "OP_1",
                    "OP_NIP",
                    "OP_NIP"
                ]
            },
            "leaves": [
                {
                    "name": "repayRefund",
                    "witness": [
                        {
                            "name": "serverSig",
                            "type": "signature",
                            "encoding": "schnorr-64",
                            "injected": true
                        },
                        {
                            "name": "senderSig",
                            "type": "signature",
                            "encoding": "schnorr-64"
                        },
                        {
                            "name": "emulatorSig",
                            "type": "signature",
                            "encoding": "schnorr-64",
                            "injected": true
                        }
                    ],
                    "asm": [
                        "<SERVER_KEY>",
                        "OP_CHECKSIGVERIFY",
                        "<senderKey>",
                        "OP_CHECKSIGVERIFY",
                        "<EMULATOR_KEY:repayRefund>",
                        "OP_CHECKSIG"
                    ]
                }
            ]
        },
        {
            "name": "reclaimWhole",
            "arkade": {
                "inputs": [],
                "asm": [
                    "<assetGidx>",
                    "<assetTxid>",
                    "<hasAsset>",
                    "<operatorKey>",
                    "OP_PUSHCURRENTINPUTINDEX",
                    "0",
                    "OP_EQUALVERIFY",
                    "0",
                    "OP_INSPECTOUTPUTSCRIPTPUBKEY",
                    "OP_NIP",
                    "1",
                    "OP_EQUALVERIFY",
                    "0",
                    "OP_INSPECTOUTPUTSCRIPTPUBKEY",
                    "OP_DROP",
                    "OP_SWAP",
                    "OP_EQUALVERIFY",
                    "0",
                    "OP_INSPECTOUTPUTVALUE",
                    "0",
                    "OP_INSPECTINPUTVALUE",
                    "OP_EQUALVERIFY",
                    "1",
                    "OP_EQUAL",
                    "OP_IF",
                    "0",
                    "OP_OVER",
                    "OP_3",
                    "OP_PICK",
                    "OP_INSPECTOUTASSETLOOKUP",
                    "OP_VERIFY",
                    "0",
                    "OP_2",
                    "OP_PICK",
                    "OP_4",
                    "OP_PICK",
                    "OP_INSPECTINASSETLOOKUP",
                    "OP_VERIFY",
                    "OP_EQUALVERIFY",
                    "OP_ENDIF",
                    "OP_1",
                    "OP_NIP",
                    "OP_NIP"
                ]
            },
            "leaves": [
                {
                    "name": "reclaimWhole",
                    "witness": [
                        {
                            "name": "serverSig",
                            "type": "signature",
                            "encoding": "schnorr-64",
                            "injected": true
                        },
                        {
                            "name": "emulatorSig",
                            "type": "signature",
                            "encoding": "schnorr-64",
                            "injected": true
                        }
                    ],
                    "asm": [
                        "<locktime>",
                        "OP_CHECKLOCKTIMEVERIFY",
                        "OP_DROP",
                        "<SERVER_KEY>",
                        "OP_CHECKSIGVERIFY",
                        "<EMULATOR_KEY:reclaimWhole>",
                        "OP_CHECKSIG"
                    ]
                }
            ]
        },
        {
            "name": "renew",
            "arkade": {
                "inputs": [],
                "asm": [
                    "0x74797065",
                    "OP_INSPECTINTENTMESSAGE",
                    "OP_VERIFY",
                    "0x7265676973746572",
                    "OP_EQUALVERIFY",
                    "0x6f6e636861696e5f6f75747075745f696e6465786573",
                    "OP_INSPECTINTENTMESSAGE",
                    "OP_VERIFY",
                    "0x5b5d",
                    "OP_EQUALVERIFY",
                    "0x636f7369676e6572735f7075626c69635f6b6579732e31",
                    "OP_INSPECTINTENTMESSAGE",
                    "OP_NIP",
                    "OP_NOT",
                    "OP_VERIFY",
                    "OP_PUSHCURRENTINPUTINDEX",
                    "1",
                    "OP_SUB",
                    "7",
                    "0",
                    "OP_TUNNEL"
                ]
            },
            "leaves": [
                {
                    "name": "renew",
                    "witness": [
                        {
                            "name": "serverSig",
                            "type": "signature",
                            "encoding": "schnorr-64",
                            "injected": true
                        },
                        {
                            "name": "emulatorSig",
                            "type": "signature",
                            "encoding": "schnorr-64",
                            "injected": true
                        }
                    ],
                    "asm": [
                        "<SERVER_KEY>",
                        "OP_CHECKSIGVERIFY",
                        "<EMULATOR_KEY:renew>",
                        "OP_CHECKSIG"
                    ]
                }
            ]
        },
        {
            "name": "exit",
            "leaves": [
                {
                    "name": "exit",
                    "witness": [
                        {
                            "name": "senderSig",
                            "type": "signature",
                            "encoding": "schnorr-64"
                        },
                        {
                            "name": "operatorSig",
                            "type": "signature",
                            "encoding": "schnorr-64"
                        }
                    ],
                    "asm": [
                        "<exitDelay>",
                        "OP_CHECKSEQUENCEVERIFY",
                        "OP_DROP",
                        "<senderKey>",
                        "OP_CHECKSIGVERIFY",
                        "<operatorSignerKey>",
                        "OP_CHECKSIG"
                    ]
                }
            ]
        }
    ]
};
